import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "./components/Footer";
import NavBar from "./components/pages/NavBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "NFlowers",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <head />
      <body className="overflow-x-hidden">

        <NavBar />      {/* ✅ OK ici */}
        {children}      {/* ✅ contenu de ta page */}
        <Footer />      {/* ✅ Footer bien à l'intérieur de <body> */}
      </body>
    </html>
     
    
  );
}
